### ISSUE TITLE
Unable to access all coins stored in veforge.vault

### ISSUE THREAD

**Issue by Atl9889** [vechain/thor-sync.electron#367]
**Describe the bug**
I used Ledger NanoX for cold storage for vault.veforge.com. Now that I am having to use Sync I can only see one of the four coins I have the the wallet. I am only able to see Vechain and not Plair coin, OceanEx coin and Safe Haven Coin which all were stored together. I hope this is an issue we can fix quickly.
**To Reproduce**
2. 
3. 
4.

**Actual result:**
Please add screenshots if needed

**Expected result:**

**Desktop OS :**
 MacOS 10.14.2/.....

**Sync Version:**

**Additional context**
None

**Comment by XJWX89** [comment]
Hi @Atl9889  you can transfer your tokens here :
MyTokens App:
Https://tokens.vecha.in/#/
VeChain Tokens App:
https://laalaguer.github.io/vechain-token-transfer/

**Comment by Fibonacci81** [comment]
same issue here.
since that "vault.veforge.com" is out of service, we've to use the new apps "Sync", however we're no more able to manage VET tokens previously stored on the Ledger Nano with Sync. 

The problem is that the VET tokens was linked on the ledger Nano and "vault.veforge.com" was able to manage them with the Ledger Nano. 
Now when trying the new app "Sync" and reading the Ledger Nano, the address where the VET tokens was linked is no more shown. 
The app "Sync" only provides 5 accounts "empty" and the account where the VET tokens are living is away from the list :/ 

Can we force the app "Sync" to choose a specific account from the Ledger Nano ? instead of only the first 5 accounts "empty". 

maybe the list into the app "Sync" should be able to show more than 5 accounts or be able to read existing accounts where VET/VTHO tokens were previously present from the Ledger Nano addresses. 

MyTokens App (Https://tokens.vecha.in/#/) doesn't help as the address where are the tokens VET cannot be linked from the Ledger Nano. 

any help appreciated, 
thanks

**Comment by Atl9889** [comment]
Yeah, still having the same issue with the MyToken app not reading my Ledger Nano as well. ths seems to be an ongoing issue.

**Comment by AsbertMa** [comment]
@Atl9889 Did you import the ledger account into MyToken?

**Comment by Atl9889** [comment]
When I attempt to import the ledger to My token and when I put in my password it temporarily reads and then it reads "INS_NOT_SUPPORTED (0x6d00)"

**Comment by AsbertMa** [comment]
@Atl9889 

1. Check version(1.0.6) of VeChain app on your device
2. Settings of app 'contract data & multi clause' to yes

**Comment by Atl9889** [comment]
Just set the "contract data & multi clause" to yes on my ledger device and Im still having the same issue.

**Comment by AsbertMa** [comment]
@Atl9889 Did you check the VeChain App version(1.0.4) on your Ledger NanoX?

**Comment by Fibonacci81** [comment]
@Atl9889 @AsbertMa 
on my side same as @Atl9889 also. 
The firmware is 1.0.6. As suggested the options "contract data & multi clause" set to yes don't give any result. 
The ledger account has been added manually into MyToken and can be read, but it doesn't help unfortunately in the previous step when importing in Wallet.

**Comment by Fibonacci81** [comment]
hello, any fix planned or workaround to solve this issue ? thanks in advance !

**Comment by XJWX89** [comment]
hi @Fibonacci81  

- Ensuring your device runs the [latest firmware](https://support.ledgerwallet.com/hc/en-us/articles/360002731113) version.
- Reinstalling the apps on your device so you run the [latest versions](https://support.ledgerwallet.com/hc/en-us/articles/360006523674). Uninstalling apps does not affect your crypto assets, that are secured on the blockchain.

**Comment by Atl9889** [comment]
Just to clarify after uninstalling Vechain from ledger and then reinstalling I am now able to log into MyToken and view all previous assets. Problem solved..

**Comment by Fibonacci81** [comment]
Thanks for the info @XJWX89, but i tried exactly the same and in my case the previous asset is still not shown unfortunately when i'm trying to import from the Ledger. 
I have uninstalled the Vechain apps, then reinstall it (version 1.0.6). Set "yes" to both options Contract-data and multi-clause. 
I also made a reset factory settings and reflash the Ledger with the last firmware. (1.6.0)
I'm using the last version of Sync 1.2.1 / Connex v1.4.0.

The apps "Sync" still provide me 5 empty accounts associated to my Ledger without the good one where my previous VET/VTHO tokens are living. 

is there any solution to have a temporary access to "vault.veforge.com" to transfer my VET tokens to another address ? 

thanks in advance for your help

**Comment by adama385** [comment]
Hello @Fibonacci81 have you found a solution? I'm having the same exact issue. I did everything you've stated to no avail. Thanks.

**Comment by XJWX89** [comment]
hi @Fibonacci81  & @adama385  , 
due to the screenshot may contain sensitive information, please send an email to support@vechain.com include below details
1. screenshot of the ledger wallet page in sync
2. screenshot of access to the achieve vault page and take a screenshot of all the wallet
3. include "github issue 367" in the email subject
Ps. you can blur some part of the address, but make sure the first 6 and last 4.

**Comment by Fibonacci81** [comment]
Hi @adama385 , unfortunately still the same issue on my side. 
i will follow the recommandation of @XJWX89 and report all requested information. 
I will update the case if any news. 
thanks.

**Comment by Fibonacci81** [comment]
Hi @XJWX89, 
thanks for your reply, I've forwarded all required information to support@vechain.com right now. 
(email subject:  [ github issue 367 ] (Re: [vechain/thor-sync.electron] Unable to access all coins stored in veforge.vault (#367))
Looking forward to hearing you.
best regards,

**Comment by adama385** [comment]
Thank you @XJWX89. Hey @Fibonacci81 I just sent them an email as recommended above.
Thanks.

**Comment by XJWX89** [comment]
sorry guys @Fibonacci81 & @adama385  , I forgot to link the achieve vault  website , please visit https://web.archive.org/web/20190615111943/https://vault.veforge.com/ and screenshot the wallets page support@vechain.com

**Comment by Fibonacci81** [comment]
hi all, 
just to update, it has been finally solved with the help of Vechain support and Ledger Support. thank you. 
I share with you the solution.

below are the recommendation :
1. we kindly ask you to ask ledger support of where you can export a specific wallet mnemonic phrase or private key.(due to the security issue, we are unable to provide any websites for this export, thanks for the understanding)
2.if you successfully get the mnemonic phrase, please import into sync or any wallets which support vechain
3. transfer the assets to a ledger wallet, which you can find in sync .

**Comment by libotony** [comment]
@Fibonacci81 Great to see you solved! I will close this issue but feel free to open a new one or contact support@vechain.com if you still have some issue @Atl9889 @adama385
