### ISSUE TITLE
Sync Wallets no longer showing my VET balance, only --.-- instead.

### ISSUE THREAD

**Issue by VeChainUser** [vechain/thor-sync.electron#461]
**Describe the bug**
Provide a brief description of the issue
My wallets in sync are no longer showing my VET balance, only displaying --.-- instead. 

does anyone know how to fix this? I've recently connected my wallet to my ledger live but it was working fine after that so idk what happened
<img width="209" alt="Screen Shot 2021-02-20 at 8 27 55 PM" src="https://user-images.githubusercontent.com/79388475/108613869-742b3780-73bb-11eb-8cd1-08987fc38f2c.png">

**To Reproduce**
2. 
3. 
4.

**Actual result:**
Please add screenshots if needed

**Expected result:**

**Desktop OS :**
 Win10/MacOS 10.14.2/.....

**Sync Version:**

**Additional context**
Any additional information, related issues, screenshots, transaction details that might be necessary to reproduce the issue

**Comment by mulitray-lab** [comment]
Experiencing the same problem.

**Comment by Dirtyazzbyrd** [comment]
I am experiencing the same issue.  Please resolve this issue quickly.

**Comment by nooh43** [comment]
refer to :
https://github.com/vechain/thor-sync.electron/issues/462

posted how it worked with me

**Comment by Humanoid1990** [comment]
Same here I am freaking out! I have 5 wallets on Sync and all show no balance just those dashes!!!! Can we get some answers here please

**Comment by radishzz** [comment]
Mine is the same I am having a problem with my VetChain Wallet I have been using it with the nano Ledger This problem started around When  I restored my Ledger with my password seed and had to reinstall the Vetchain app on my Ledger again Since then when I login to my VetChain sync account the balance does not show I have to click on my Dashborad Then the page reloads and I can see my cash balance But my VetChain Token amount is not there It shows  like this   ---------VET But the cash balance is there also my recent transfers are not there and there is tinny circle spinning as if its trying to load my recent transfers I just sent some more VetChain to my wallet to see if it would load my recent transfers But it did not work But it added the VetChain to my balance I also tried to see if I could send any of my VetChain out of the wallet  and it is coming up as zero balance  Could you help me please I would be so greatful Like I say the balance is there Once I click on my Dashbord
![DFS](https://user-images.githubusercontent.com/79395495/108618573-36f49300-7417-11eb-87a7-6c10f952de3a.PNG)

**Comment by radishzz** [comment]
![1111QCapture](https://user-images.githubusercontent.com/79395495/108618588-4378eb80-7417-11eb-8ea6-51013471cb5f.PNG)
![1111QCapture](https://user-images.githubusercontent.com/79395495/108618607-5f7c8d00-7417-11eb-8064-3e3b323b5d71.PNG)

**Comment by libotony** [comment]
Sorry for the inconvenience, I believe the issue has been solved. Closing this now, feel free to reopen this.

**Comment by radishzz** [comment]
All sorted Guys updated the nod Thanks for getting in touch though Great customer service
